[package]
name = "zlib"
authors = [ "C2Rust",]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "zlib"
path = "lib.rs"
crate-type = [ "cdylib",]

[dependencies]
errno = "0.3"
rustix = { version = "1", features = ["fs", "stdio", "try_close"] }

[workspace]
members = []
default-members = [ ".",]

[profile.release]
strip = "debuginfo"
